language: node_js
node_js:
- "4"
- "5"

install:
- npm install

script:
- npm pack
# And now test that the sample can run
- cd sample
- npm install
- npm install ../grunt-mermaid-0.9.1.tgz
- npm install grunt
- npm install grunt-cli -g
- grunt mermaid:default
- grunt mermaid:other

deploy:
  provider: npm
  email: "jesper@balle-net.dk"
  api_key:
    secure: "IPSWLqYv+qP3iFHvpmSHRDaRMCJQ49gnEfm5Qu2y0tXMDmjGlxBCqVOsIjzTfVtejG/YL8iAagnzR8rl9CGLs5vVMSSF4idPywyFaJLPf+ZHa8E4Al3k2P22q/1rksvhqkx9yf8SKzg4zsvaVFkj3gfL3jHjEvtkzMDL40nNxCw0dsaz0rkhwPOEfnOeckhZphVpdbBg/KM5iWMTpB6GKVEkarKy3RVkgCBy+yZ0DEAMB5mtbAe967Ij1awyI2UymPYkSKIJezEuoN0U/T/o7l4bVWMg5+ilplOjN3BYKu2VI1hUjimP/1AKppColfoWSCkLZ6Pf7nSUSBIOYBxKtuK/6UmrOfrEhm5Vg4cRjUSU9J1WgY1E/UAVALqy2v77gZTuZL/ityYQNl3yVutU/7LA+0Jwg78R6V1jbdCf+5+06vgHKWDHaal8+OrYTjdCVtaSZ4dPfbzABrfGaUwafpb84M3DYswLyE2aCBCjkTUcRQ6qtN+VNwEe0sMEkkU/1ZRLYm0Yae/KQxr2Aockk64ERxxvsIsSU2Uf25quJ1Imh0VO7JEOEBeQXySpT1qY67dT4wCU0KPZ/PTfgR5yj76zLIRD97BwOPzHww+r4YiJzo9S0rj48Kt55vk7QzxOCIJnFAWMvb6akJQekRU6mmqeImky7jH6alarTGDWneg="
  on:
    tags: true
    
   