language: node_js
node_js:
- "4"

install:
- npm install

script:
- npm pack
# And now test that the sample can run
- cd sample
- npm install
- npm install ../grunt-mermaid-0.9.0.tgz
- npm install grunt
- npm install grunt-cli -g
- grunt mermaid:default
- grunt mermaid:other

deploy:
  provider: npm
  email: "jesper@balle-net.dk"
  api_key:
    secure: "ntIk621Q3bW58VgwZzjcQ7lhXSklz1X5/gnAML3bPrgyjdW2z4tHBqTF89py3GBc5SU8wZBDpgXPk53TK5tZIh61SSDsN+JfrWCvOESZ3WFriy97sDMZpVaGj2atBzVgz6MZuMVRZ1M5YO8qQG/K9U+2yyZg1e4bdN0CkV+kA7JvM47GiGOyBw/3JGHq1y7XLgujJaiFBhBMk4lmSLQvmhtpnWFh3HFrhp91cIv1EwOwuxED2JiGb3gHhCew6dXgl7tf8oRjBVEbhvSQCM3Gi5WsgLNv6ja0Y8lFf6InwOp/ReZRTX3asDOVJaeI+NJJCDNqqeNT2mfq+JGW5Vle83rLN8ZEvCiZb8IR3flPkf7WD879igH7f4hIYBY4dR3CUnx8aUb0hH9IDBKDXnuyo195rI8Q7C++cIV6T+oM2ovO+kbHgg5iTRwONj5WUGoaJit5k+zcVsNmYO2AOEexgchpfCgruKdHM+wzF8mzZANFypA1wjRFaiBvhJ6/3towlgzVpdD6dTF6a9bDL4B0/tqUXy7E33iYO6colXC4H99rqb0FOUwVbgtjC1xEh3r4yGFdUTfCgFS2mT2U5b4+1ra2KqnI1VrjwMV1Gx5seUTzbf5OhVrfxBnGlXHd+lFRKfltQnbh2A4f2Nwqj/7viJbrSrJyjSayY5Pv/T9Dn4k="
  on:
    tags: true
    
   