language: node_js
node_js:
- "4"

install:
- npm install

script:
- npm pack
# And now test that the sample can run
- cd sample
- npm install
- npm install ../grunt-mermaid-0.9.0.tgz
- npm install grunt
- npm install grunt-cli -g
- grunt mermaid:default
- grunt mermaid:other

deploy:
  provider: npm
  email: "jesper@balle-net.dk"
  api_key:
    secure: "WpCakYoVnkQj3KZpBbdzg8+QoR51qSrEuF7AVeZRwatqzovjdYE1RRQpwWav+gEhBDW2mmgwFy+ekwVBbB4uIMr2AerFZJzpBLK7GwtHM7INfvWY+C799radpGf7yjeaAla67bVmuiJMRpsf98hDZjNqqh9AJGyafc+fqx7cI82VKI3SW950LZF4UBi+2ILktjC1fwlMO7suzbUs1W6S+tnXcAuxq0JF8vI158cqnEbH+k3k9A3HmKskEdARNJ6d3P9FNF5rMNslfrrop3d+Es03QKbnHFl9D1me7cdTb1PfRA79/o36FX8JfUy60LuA4nt4YmBuMT5Oo5FB49LOLoaXBqkFO+WN7hDPRHl2j0AMZJBTawFfkdhQoQKYXfX44Zxt5XWnVMqP1RTjevplfS6zQecwvdufT0jK71lBSnBh928RRBUAKfAMZYZ0vQVMPJkATkgSIu4t82UDjTyL/+qUvmgDYFmuGIqL0MmsyurzZBjtBolg7cYC9WmnWL9aXR+J02oY+dgH4MldlM2KE9+XMAYBqoApCnTfr80pUWOlWsj9MyQWS9nXLMDGYFVu59ztAbm1YPrFY4jtKzn9WsWXrXNv6reh4Yq+CHFTNbC8ukvwXFeckO9OIEdvzDQH2oKLTmpm/VOM4QVD7cTlABtUn5k8MwV6XNQcXmO5db0="
  on:
    tags: true
    
   